# Global Content
title: A JavaScript Client for the WordPress REST API
library_title: node-wpapi
description: > # this means to ignore newlines until "baseurl:"
  Node-WPAPI is a flexible, fluent client for the WordPress REST API
  that works both on the server and in the browser. It lets you easily
  filter and query WordPress for specific data, create or update content
  within your WordPress database, and more.

# Domain Configuration
baseurl: "/node-wpapi" # the subpath of your site, e.g. /blog
url: "http://wp-api.org" # the base hostname & protocol for your site

# Social Media
github_username:  wp-api/node-wpapi
gitter_url: gitter.im/wp-api/node-wpapi
twitter_username: kadamwhite

# Build settings
markdown: kramdown
exclude: ["*.combyne"]
